/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:540ba2fb-ed7c-4080-8fb9-87708467d748",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6t3YjJwnK",
    "aws_user_pools_web_client_id": "ttpa1lte9r1mt9k9ejk709r20",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://6lsp4cukcrbudjq57jcfdv4oz4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-apa7aspkxvedlfwpnvgbmtxp5u",
    "aws_user_files_s3_bucket": "amplifyreactgraphql-storage-bucketc95f1-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
